# Generated by Django 4.0.6 on 2022-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_place_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellingplaces',
            name='summarized_description',
            field=models.JSONField(default=None, null=True),
        ),
    ]
